import { CctvCamera, Violation } from "./types";

export const INITIAL_CAMERAS: CctvCamera[] = [
  {
    id: "CAM-01",
    name: "Kamera 01 - Bundaran HI (Utara)",
    location: "Jl. MH Thamrin, Jakarta Pusat",
    lat: -6.1919,
    lng: 106.8240,
    status: "Aktif",
    ipAddress: "192.168.10.101",
    violationsCount24h: 34,
    feedType: "helmet",
  },
  {
    id: "CAM-02",
    name: "Kamera 02 - Layang Casablanka",
    location: "Karet Kuningan, Jakarta Selatan",
    lat: -6.2241,
    lng: 106.8315,
    status: "Aktif",
    ipAddress: "192.168.10.102",
    violationsCount24h: 18,
    feedType: "speed",
  },
  {
    id: "CAM-03",
    name: "Kamera 03 - Simpang Harmoni",
    location: "Jl. Gajah Mada, Jakarta Pusat",
    lat: -6.1604,
    lng: 106.8214,
    status: "Aktif",
    ipAddress: "192.168.10.103",
    violationsCount24h: 52,
    feedType: "red_light",
  },
  {
    id: "CAM-04",
    name: "Kamera 04 - Gatot Subroto (Polda)",
    location: "Jl. Jend. Gatot Subroto, Jakarta Selatan",
    lat: -6.2238,
    lng: 106.8124,
    status: "Aktif",
    ipAddress: "192.168.10.104",
    violationsCount24h: 27,
    feedType: "phone",
  },
  {
    id: "CAM-05",
    name: "Kamera 05 - Semanggi Interchange",
    location: "Karet Semanggi, Jakarta Selatan",
    lat: -6.2198,
    lng: 106.8122,
    status: "Pemeliharaan",
    ipAddress: "192.168.10.105",
    violationsCount24h: 0,
    feedType: "normal",
  },
  {
    id: "CAM-06",
    name: "Kamera 06 - Simpang Sudirman",
    location: "Simpang Sudirman, Jakarta",
    lat: -6.2146,
    lng: 106.8229,
    status: "Aktif",
    ipAddress: "192.168.10.106",
    violationsCount24h: 124,
    feedType: "normal",
  },
  {
    id: "CAM-07",
    name: "Kamera 07 - Tomang Raya",
    location: "Tomang Raya, Jakarta Barat",
    lat: -6.1770,
    lng: 106.7900,
    status: "Aktif",
    ipAddress: "192.168.10.107",
    violationsCount24h: 34,
    feedType: "normal",
  },
  {
    id: "CAM-08",
    name: "Kamera 08 - Kuningan",
    location: "Kuningan, Jakarta Selatan",
    lat: -6.2250,
    lng: 106.8320,
    status: "Aktif",
    ipAddress: "192.168.10.108",
    violationsCount24h: 92,
    feedType: "helmet",
  },
  {
    id: "CAM-09",
    name: "Kamera 09 - Pondok Indah",
    location: "Pondok Indah, Jakarta Selatan",
    lat: -6.2800,
    lng: 106.7800,
    status: "Aktif",
    ipAddress: "192.168.10.109",
    violationsCount24h: 15,
    feedType: "speed",
  },
  {
    id: "CAM-10",
    name: "Kamera 10 - Kelapa Gading",
    location: "Kelapa Gading, Jakarta Utara",
    lat: -6.1600,
    lng: 106.9000,
    status: "Aktif",
    ipAddress: "192.168.10.110",
    violationsCount24h: 45,
    feedType: "normal",
  },
  {
    id: "CAM-11",
    name: "Kamera 11 - Cawang",
    location: "Cawang, Jakarta Timur",
    lat: -6.2400,
    lng: 106.8700,
    status: "Aktif",
    ipAddress: "192.168.10.111",
    violationsCount24h: 110,
    feedType: "phone",
  },
  {
    id: "CAM-12",
    name: "Kamera 12 - Slipi",
    location: "Slipi, Jakarta Barat",
    lat: -6.1950,
    lng: 106.7950,
    status: "Aktif",
    ipAddress: "192.168.10.112",
    violationsCount24h: 28,
    feedType: "red_light",
  }
];

export const INITIAL_VIOLATIONS: Violation[] = [
  {
    id: "ETLE-2026-8911",
    licensePlate: "B 1234 SMN",
    vehicleType: "Motor",
    vehicleModel: "Honda Beat FI (Maju Jaya)",
    violationType: "Tidak Menggunakan Helm Standar (SNI)",
    location: "CAM-01 - Bundaran HI (Utara)",
    timestamp: "2026-07-10T08:15:30",
    fineAmount: 250000,
    status: "Belum Bayar",
    ownerName: "Budi Santoso",
  },
  {
    id: "ETLE-2026-4422",
    licensePlate: "B 1088 TQA",
    vehicleType: "Mobil",
    vehicleModel: "Toyota Fortuner 2.8 VRZ",
    violationType: "Melebihi Batas Kecepatan Maksimum (132 km/h)",
    location: "CAM-02 - Layang Casablanka",
    timestamp: "2026-07-10T09:44:12",
    fineAmount: 500000,
    status: "Lunas",
    ownerName: "PT Sinar Sejahtera",
    speedKmh: 132,
  },
  {
    id: "ETLE-2026-5511",
    licensePlate: "F 1422 RX",
    vehicleType: "Mobil",
    vehicleModel: "Honda Civic Turbo Sedan",
    violationType: "Menggunakan Telepon Genggam Saat Mengemudi",
    location: "CAM-04 - Gatot Subroto (Polda)",
    timestamp: "2026-07-10T10:12:05",
    fineAmount: 750000,
    status: "Belum Bayar",
    ownerName: "Ahmad Rifai",
  },
  {
    id: "ETLE-2026-7734",
    licensePlate: "AD 8452 CB",
    vehicleType: "Mobil",
    vehicleModel: "Daihatsu Xenia Silver",
    violationType: "Menerobos Lampu Merah (Rambu APILL)",
    location: "CAM-03 - Simpang Harmoni",
    timestamp: "2026-07-10T11:03:55",
    fineAmount: 500000,
    status: "Proses Banding",
    ownerName: "Siti Rahmawati",
  },
  {
    id: "ETLE-2026-9088",
    licensePlate: "B 9482 WPZ",
    vehicleType: "Motor",
    vehicleModel: "Yamaha NMAX 155 ABS",
    violationType: "Melanggar Markah Jalan / Stop Line",
    location: "CAM-01 - Bundaran HI (Utara)",
    timestamp: "2026-07-09T17:35:10",
    fineAmount: 500000,
    status: "Lunas",
    ownerName: "Hendra Wijaya",
  },
  {
    id: "ETLE-2026-1289",
    licensePlate: "B 1988 TRD",
    vehicleType: "Truk",
    vehicleModel: "Hino Dutro Cargo",
    violationType: "Pelanggaran Pembatasan Jam Operasional Truk",
    location: "CAM-04 - Gatot Subroto (Polda)",
    timestamp: "2026-07-09T14:22:15",
    fineAmount: 250000,
    status: "Belum Bayar",
    ownerName: "CV Transport Express",
  }
];

export interface LawArticle {
  id: string;
  pasal: string;
  category: string;
  fine: number;
  description: string;
}

export const LAW_ARTICLES: LawArticle[] = [
  {
    id: "PASAL-291-1",
    pasal: "Pasal 291 ayat (1)",
    category: "Tidak Memakai Helm",
    fine: 250000,
    description: "Setiap pengendara sepeda motor yang tidak mengenakan helm standar nasional Indonesia (SNI).",
  },
  {
    id: "PASAL-291-2",
    pasal: "Pasal 291 ayat (2)",
    category: "Membiarkan Penumpang Tanpa Helm",
    fine: 250000,
    description: "Setiap pengemudi sepeda motor yang membiarkan penumpangnya tidak mengenakan helm SNI.",
  },
  {
    id: "PASAL-289",
    pasal: "Pasal 289",
    category: "Tidak Memakai Sabuk Pengaman",
    fine: 250000,
    description: "Pengemudi atau penumpang di samping pengemudi mobil yang tidak mengenakan sabuk keselamatan.",
  },
  {
    id: "PASAL-287-2",
    pasal: "Pasal 287 ayat (2)",
    category: "Menerobos Lampu Merah",
    fine: 500000,
    description: "Setiap orang yang mengemudikan kendaraan bermotor yang melanggar aturan alat pemberi isyarat lalu lintas (APILL).",
  },
  {
    id: "PASAL-283",
    pasal: "Pasal 283",
    category: "Menggunakan HP Saat Mengemudi",
    fine: 750000,
    description: "Setiap orang yang mengemudikan kendaraan secara tidak wajar dan melakukan kegiatan lain atau dipengaruhi keadaan yang mengakibatkan gangguan konsentrasi (seperti bermain ponsel).",
  },
  {
    id: "PASAL-287-5",
    pasal: "Pasal 287 ayat (5)",
    category: "Melanggar Batas Kecepatan",
    fine: 500000,
    description: "Setiap orang yang mengemudikan kendaraan bermotor melanggar aturan batas kecepatan paling tinggi atau paling rendah.",
  },
  {
    id: "PASAL-280",
    pasal: "Pasal 280",
    category: "Tanpa Plat Nomor (TNKB)",
    fine: 500000,
    description: "Setiap orang yang mengemudikan kendaraan bermotor di jalan yang tidak dipasangi tanda nomor kendaraan bermotor (TNKB/Plat Nomor) resmi.",
  }
];

// Sample images preset data
export const SAMPLE_PRESETS = [
  {
    id: "preset_helmet",
    name: "Pengendara Tanpa Helm",
    type: "helmet",
    imageName: "helmet_violation.jpg",
    imageUrl: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=600&q=80",
    description: "Sepeda motor melaju di jalan protokol dengan pengendara tidak mengenakan pelindung kepala (helm).",
  },
  {
    id: "preset_speed",
    name: "Mobil Kecepatan Tinggi (Speeding)",
    type: "speed",
    imageName: "speed_violation.jpg",
    imageUrl: "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=600&q=80",
    description: "Sebuah mobil melintas sangat cepat di jalan tol malam hari terekam oleh kamera speed radar.",
  },
  {
    id: "preset_phone",
    name: "Pengemudi Menggunakan HP",
    type: "phone",
    imageName: "phone_violation.jpg",
    imageUrl: "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?auto=format&fit=crop&w=600&q=80",
    description: "Pengemudi terlihat menunduk memegang gawai/handphone sewaktu mengemudi di tengah kemacetan.",
  },
  {
    id: "preset_red_light",
    name: "Mobil Menerobos Lampu Merah",
    type: "red_light",
    imageName: "red_light_violation.jpg",
    imageUrl: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=600&q=80",
    description: "Kendaraan tetap memacu laju menyeberangi persimpangan meskipun lampu isyarat lalu lintas menyala merah.",
  }
];
